### ISSUE TITLE
Licence type?

### ISSUE THREAD

**Issue by MagnetarRocket** [B00merang-Project/B00merang-Blackout#4]
Unlike the other themes of the b00merang project, blackout does not have a stated license type. Also as of late someone else has released a re-colored version of blackout with the default C64 KERNAL prompt colors (https://www.gnome-look.org/p/2067565).

**Comment by Elbullazul** [comment]
thanks for letting me know. The theme should have the same GPLv3 license as the other themes, I'll add a license file later today.

**Comment by Elbullazul** [comment]
addresses by [6876a22](https://github.com/B00merang-Project/B00merang-Blackout/commit/6876a2215120e3225282c7e1249a8ab2d8f8a435)
